version: '3.4'

services:
  github-inspector:
    image: ${DOCKER_REGISTRY-}github-inspector
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    build:
      context: .
      dockerfile: GithubInspector/Dockerfile
    ports:
      - 50000:443

  redis:
    image: redis/redis-stack:latest
    ports: 
      - 6379:6379